### ISSUE TITLE
Android does not works 

### ISSUE THREAD

**Issue by bigmoveus** [NavidShokoufeh/sstp_flutter#1]
Hi compile for Android and cannot connect to SSTP server with valid certificate and in log can see this error only 
OSC: ERR_UNEXPECTED

If you want I Can share the SSTP server details that work over mikrotik

**Comment by NavidShokoufeh** [comment]
Hi,
please get in touch with navidshokoufeh.dev@gmail.com and send your sstp config and steps which you have done.

**Comment by bigmoveus** [comment]
Hi details already sent .
Thanks

**Comment by NavidShokoufeh** [comment]
this is the exception :
> Trust anchor for certification path not found.

do you have trusted certificate for your server?
if yes, let me know to release the new version that supports certificates.

also refer to [issue55](https://github.com/kittoku/Open-SSTP-Client/issues/55)

**Comment by bigmoveus** [comment]
Hi yes server working with trusted certificate I think If we have this ability that working with both way will be great !

**Comment by NavidShokoufeh** [comment]
sure, in few days the new version which involves certificate will be published.

**Comment by NavidShokoufeh** [comment]
@bigmoveus 
check out the new version (1.0.6) and let me know if your problem persists.
note : you have to change ```useTrustedCert``` in your```SSTPServer```  to ```true``` to use the provided path by ```addCertificate()```

**Comment by blueboy-tm** [comment]
I had the same problem. After debugging, I realized that SSLContext was giving an error because my host didn't have a valid certificate. In this pull request https://github.com/NavidShokoufeh/sstp_flutter/pull/11, you can set verifySSLCert to false

**Comment by NavidShokoufeh** [comment]
Pull request [#11](https://github.com/NavidShokoufeh/sstp_flutter/pull/11) has been merged in version [1.1.0](https://pub.dev/packages/sstp_flutter) . 
You can update your dependency. Thanks to [Arshia Eihami](https://github.com/blueboy-tm) .
