### ISSUE TITLE
Building for 'iOS-simulator', but linking in object file 

### ISSUE THREAD

**Issue by MrFantuk** [NavidShokoufeh/sstp_flutter#12]
Error (Xcode): Building for 'iOS-simulator', but linking in object file (/Users/denis/.pub-cache/hosted/pub.dev/sstp_flutter-1.2.0+hotfix.2/ios/ext/ExtParser.framework/ExtParser[3](SimplePing.o)) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro Max.

All install steps done.
using: sstp_flutter: ^1.2.0+hotfix.2
sdk: ">=3.0.0 <4.0.0"

**Comment by NavidShokoufeh** [comment]
Hello , 
The ExtParser framework doesn't support x86_64 architecture so it's can not be run on iOS simulator unless real devices

**Comment by MrFantuk** [comment]
Thank you)
