### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by smj1234** [NavidShokoufeh/sstp_flutter#14]
salam - aziz id telegram midi ye sohbati bokonim dar rabete ba ey proje?

**Comment by NavidShokoufeh** [comment]
سلام 
بهم یه ایمیل بدید بفرستم براتون
navidshokoufeh.dev@gmail.com

**Comment by smj1234** [comment]
![image](https://github.com/user-attachments/assets/f9427f38-3b77-4b59-a7db-53f4d0f7346a)

**Comment by NavidShokoufeh** [comment]
@smj1234 ادیت شد
