### ISSUE TITLE
i nedd to add my own cert from internal assets files

### ISSUE THREAD

**Issue by it-ahmednour** [NavidShokoufeh/sstp_flutter#2]
hello sir
thanks for this package
how i can add my own certificate from internal assets
Is it possible to connect without a certificate?

**Comment by NavidShokoufeh** [comment]
Hi,
checkout the new version (1.0.7)
first of all define these properties (```useTrustedCert: true, sslVersion: SSLVersions.DEFAULT,```)  in ```SSTPServer```, and then select the folder which involves your certificate using ```cert_dir = await sstpFlutterPlugin.addCertificate();```
NOTE: you have to change ```SSLVersions``` from default to any supported version.

let me know if your problem persists.

**Comment by it-ahmednour** [comment]
I have already tried the connection through version 1.0.6
By using a ssl certificate, I manually specify its folder
I am asking about the possibility of integrating my ssl certificate into my
application or connecting without need a ssl certificate

**Comment by it-ahmednour** [comment]
I have some problems after upgrade version to 1.0.7
[image: image.png]

**Comment by NavidShokoufeh** [comment]
>I am asking about the possibility of integrating my ssl certificate into my application or connecting without need a ssl certificate.

I'm working on that , i will add it if be possible.

**Comment by NavidShokoufeh** [comment]
> I have some problems after upgrade version to 1.0.7 [image: image.png]

Please provide some information about you problem. snippet code , error or anything else that you think i can help you with.

**Comment by it-ahmednour** [comment]
This would be great
Thank you very much
I wish you success always
If you need a STP account to try out, this is a special account for you
server => win.mega-tik.com
port => 443
user => navidshokoufeh
pass => navidshokoufeh
ssl_cert => attached
My greetings to you

**Comment by it-ahmednour** [comment]
i just use you example main.dart without any changes

[image: image.png]

**Comment by NavidShokoufeh** [comment]
> i just use you example main.dart without any changes [image: image.png]

The account you provided with certificate you sent me works correctly by the example of package, and i can't figure out your problem because your image is not attached.

**Comment by it-ahmednour** [comment]
![Uploading Screenshot 2024-01-08 113413.png…]()

**Comment by NavidShokoufeh** [comment]
https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d#file-cdn-md

**Comment by it-ahmednour** [comment]
i fix my errors by delete old package version folder from windows app_data cache directory
thanks my bro

**Comment by it-ahmednour** [comment]
look here => https://chat.openai.com/share/09cadb9f-216b-4a4e-877e-611661044b14
you can edit SSLTerminal.kt to add your own certificate from internal raw folder

**Comment by NavidShokoufeh** [comment]
> look here => https://chat.openai.com/share/09cadb9f-216b-4a4e-877e-611661044b14 you can edit SSLTerminal.kt to add your own certificate from internal raw folder

thanks , i will consider it.
