### ISSUE TITLE
Change notification icon

### ISSUE THREAD

**Issue by RProduction** [NavidShokoufeh/sstp_flutter#3]
Hey, thank you for this library.
Really save me.
Changing from openvpn to this library solve my relay client problem.

I need to know how to change small app icon in notification because it showing flutter icon.
How to do it? Maybe a way to add meta-data for default icon?

**Comment by NavidShokoufeh** [comment]
Hello,
I'm glad to hear that. I will work on the notification icon and will let you know in this issue.

**Comment by NavidShokoufeh** [comment]
Hi , now [SSTP plugin](https://github.com/NavidShokoufeh/sstp_flutter/tree/main) uses the app default icon. you have to customize your app icon for this purpose.

**Comment by RProduction** [comment]
Thank you for the change
