### ISSUE TITLE
Foreground Service crashing on Android 14

### ISSUE THREAD

**Issue by H3mnz** [NavidShokoufeh/sstp_flutter#5]
When I try to connect to vpn on targetSDK 34, this error happened.

android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{f966549 31871} targetSDK=34

**Comment by NavidShokoufeh** [comment]
Thank to your participation it solved [#6](https://github.com/NavidShokoufeh/sstp_flutter/pull/6). As it fixed i close this issue.
